# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.Calendar.setGeometry(QtCore.QRect(70, 50, 351, 211))
        font = QtGui.QFont()
        font.setKerning(True)
        self.Calendar.setFont(font)
        self.Calendar.setGridVisible(False)
        self.Calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.Calendar.setNavigationBarVisible(False)
        self.Calendar.setDateEditEnabled(True)
        self.Calendar.setObjectName("Calendar")
        self.StartPush = QtWidgets.QPushButton(self.centralwidget)
        self.StartPush.setGeometry(QtCore.QRect(430, 70, 75, 23))
        self.StartPush.setObjectName("StartPush")
        self.StopPush = QtWidgets.QPushButton(self.centralwidget)
        self.StopPush.setGeometry(QtCore.QRect(430, 110, 75, 23))
        self.StopPush.setObjectName("StopPush")
        self.Autoradio = QtWidgets.QRadioButton(self.centralwidget)
        self.Autoradio.setGeometry(QtCore.QRect(430, 150, 82, 17))
        self.Autoradio.setObjectName("Autoradio")
        self.video = QVideoWidget(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(70, 280, 431, 251))
        self.video.setObjectName("video")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartPush.setText(_translate("MainWindow", "Start"))
        self.StopPush.setText(_translate("MainWindow", "Stop"))
        self.Autoradio.setText(_translate("MainWindow", "Autostart"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
